ALTER TABLE products ADD COLUMN tagline TEXT;
ALTER TABLE products ADD COLUMN is_bestseller INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN rating DECIMAL(2,1) DEFAULT 5.0;
ALTER TABLE products ADD COLUMN reviews INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN sold INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN features TEXT;
ALTER TABLE products ADD COLUMN faq TEXT;
