name = "eyrya-website"
compatibility_date = "2024-03-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "eyrya-db"
database_id = "c20eb39e-0cd3-4c3b-ba8d-f8115622b311"

# R2 存储桶绑定
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "eyrya-images"
